### ISSUE TITLE
Potential upgrade issues when upgrading from Drupal 7

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/taxonomy_access#16]
Taxonomy Access configuration settings don't seem to be transferring in a D7 upgrade and all levels are disabled on the new upgraded site.

> Notice: Undefined index: taxonomy_access_global_default in taxonomy_access_admin_role() (line 238 of /app/modules/contrib/taxonomy_access/taxonomy_access.admin.inc).

> TypeError: Argument 1 passed to taxonomy_access_admin_build_row() must be of the type array, null given, called in /app/modules/contrib/taxonomy_access/taxonomy_access.admin.inc on line 445 in taxonomy_access_admin_build_row() (line 521 of /app/modules/contrib/taxonomy_access/taxonomy_access.admin.inc).

**Comment by laryn** [comment]
Initial glance suggests the vocabulary values in the `taxonomy_access_default` table did not get converted from `vid` to `machine_name`.

**Comment by laryn** [comment]
Manually replacing the numeric `vid` values with the respective `machine_name` values (and `taxonomy_access_global_default` for value `0`) seems to be all that was needed to get things functional again.

**Comment by laryn** [comment]
This should be already happening here:

https://github.com/backdrop-contrib/taxonomy_access/blob/1.x-1.x/taxonomy_access.install#L336-L347

On the site in question, a separate module crashed the update process and I restarted it halfway through after patching the module. I'm not sure if that short-circuited something or not. I'll leave this open for now but perhaps it's already fixed...

**Comment by herbdool** [comment]
It seems to have failed in my case too.

This client has a lot of settings so I may attempt to write an update hook as a one off and maybe I'll discover why it didn't work the first time.

**Comment by herbdool** [comment]
And when I attempt to enable it for anon and authenticated roles, I get:

> Error message
> Warning: Undefined array key "taxonomy_access_global_default" in taxonomy_access_admin_role() (line 238 of /app/httpdocs/modules/contrib/taxonomy_access/taxonomy_access.admin.inc).
> TypeError: taxonomy_access_admin_build_row(): Argument #1 ($grants) must be of type array, null given, called in /app/httpdocs/modules/contrib/taxonomy_access/taxonomy_access.admin.inc on line 445 in taxonomy_access_admin_build_row() (line 521 of /app/httpdocs/modules/contrib/taxonomy_access/taxonomy_access.admin.inc).

**Comment by herbdool** [comment]
One thing (though I'm not sure if this has caused specific issues): there's no guarantee that constants, which were defined in the `.module` file, are available in `.install` file during upgrades. Especially if the module was installed but wasn't enabled.

**Comment by herbdool** [comment]
Here's an issue. It is only checking that `taxonomy_vocabulary` table exists but it's likely by the time this hook runs, that vocabulary has already been converted to config. So there should be a backup plan to check those.

**Comment by herbdool** [comment]
Darn, don't have access to the old `vid` then. Would need a way to have the update run before `taxonomy_update_1002`. Otherwise it runs too late.

**Comment by herbdool** [comment]
I think this will help: https://docs.backdropcms.org/api/backdrop/core!modules!system!system.api.php/function/hook_update_dependencies/1

It will give it a chance to run before `taxonomy_update_1002()`. But if the core updates have already happened then the dependency will just be ignored, which is no worse off than what happens currently. I think this will work if put into `taxonomy_access.install`:

```
/**
 * Implements hook_update_dependencies().
 */
function taxonomy_access_update_dependencies {
  $dependencies['taxonomy'][1002] = array(
    'taxonomy_access' => 1000,
  );
  return $dependencies;
}
```

**Comment by herbdool** [comment]
Another problem: the update hooks should probably also update `taxonomy_access.settings` and assign a `gid` to each row. I managed to convert the table but it still doesn't have a gid per role.

**Comment by herbdool** [comment]
I added a PR. I haven't tested the update hook dependency (yet). I moved the assigning of `TAXONOMY_ACCESS_GLOBAL_DEFAULT` outside of checking for `taxonomy_vocabulary` since it's not dependent on that. And I added a hook to assign gid per role.

**Comment by herbdool** [comment]
For those wanting to convert the tables but have already upgraded (but have access to their old d7 db), they can add a hook in a custom module and do something like this where they hardcode the vid and machine_name of each vocabulary from the d7 db:

```
/**
 * Try convert the vocabularies again.
 */
function mymodule_update_1000() {
  // Convert the vocabularies.
  $vocabulary_names = array(
    8 => 'apple_types',
    5 => 'orange_types',
    7 => 'potato_types',
  );

  foreach ($vocabulary_names as $vid => $machine_name) {
    db_query('
      UPDATE {taxonomy_access_default}
      SET vocabulary = :machine_name
      WHERE vocabulary = :vid
      ', array(':vid' => $vid, ':machine_name' => $machine_name));
  }

  db_query('
      UPDATE {taxonomy_access_default}
      SET vocabulary = :machine_name
      WHERE vocabulary = :vid
      ', array(':vid' => 0, ':machine_name' => TAXONOMY_ACCESS_GLOBAL_DEFAULT));
}
```

**Comment by laryn** [comment]
Thanks @herbdool -- this is in https://github.com/backdrop-contrib/taxonomy_access/releases/tag/1.x-1.0.1
