### ISSUE TITLE
Undefined property: stdClass::$role in taxonomy_access_user_role_delete() 

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/taxonomy_access#17]
`Warning: Undefined property: stdClass::$role in taxonomy_access_user_role_delete() (line 231 of /app/httpdocs/modules/contrib/taxonomy_access/taxonomy_access.module).`

It stops complaining when I change it to `$role->name`.

**Comment by herbdool** [comment]
@laryn I've got a PR.

**Comment by laryn** [comment]
Thanks @herbdool -- merged.
