### ISSUE TITLE
Needs hook_config_info()

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/taxonomy_access#19]
I noticed a `taxonomy_access.settings` so it'll need a `hook_config_info()` so config can be updated/exported/imported.

**Comment by herbdool** [comment]
This has a PR now @laryn

**Comment by herbdool** [comment]
@laryn would you have a chance to merge and make a new release? I'm currently forking this for a client.

**Comment by laryn** [comment]
Thanks @herbdool -- this is in https://github.com/backdrop-contrib/taxonomy_access/releases/tag/1.x-1.0.1
